# Generated by Django 3.2.7 on 2021-10-18 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.SlugField(default='course-code-not-applicable', max_length=30)),
                ('is_pub', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=40)),
                ('intructor_email', models.EmailField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('team_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_teams', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_project', to='project_allocation.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_roll_num', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('student_email', models.EmailField(max_length=40, unique=True)),
                ('student_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_enrolled', to='project_allocation.course')),
                ('student_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roll_enrolled', to='project_allocation.student')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_pref', to='project_allocation.course')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_pref', to='project_allocation.project', verbose_name='Project Name')),
                ('student_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_pref', to='project_allocation.student')),
            ],
        ),
        migrations.CreateModel(
            name='Peer_edges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(default='N', max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_peer', to='project_allocation.course')),
                ('peer_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_id_peer', to='project_allocation.student')),
                ('student_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_peer', to='project_allocation.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_allocation.instructor'),
        ),
        migrations.AddConstraint(
            model_name='projects_pref',
            constraint=models.UniqueConstraint(fields=('course_id', 'student_roll_num', 'project_id'), name='unique_pref'),
        ),
        migrations.AddConstraint(
            model_name='peer_edges',
            constraint=models.UniqueConstraint(fields=('course_id', 'student_roll_num', 'peer_roll_num'), name='unique_edges'),
        ),
    ]
