# Generated by Django 3.2.8 on 2021-10-09 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('team_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_teams', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_pub', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='project_allocation.course')),
            ],
        ),
    ]
