# Generated by Django 3.2.7 on 2021-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allocation_data',
            constraint=models.UniqueConstraint(fields=('student_roll_num', 'course_id'), name='unique_allocation'),
        ),
    ]
