# Generated by Django 3.2.8 on 2021-10-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.SlugField(default='course-code-not-applicable', max_length=30),
        ),
    ]
