# Generated by Django 3.2.8 on 2021-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0004_auto_20211009_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_pub',
        ),
        migrations.AddField(
            model_name='course',
            name='is_pub',
            field=models.BooleanField(default=False),
        ),
    ]
