# Generated by Django 3.2.8 on 2021-10-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0005_auto_20211009_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_pref', to='project_allocation.course')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_pref', to='project_allocation.project')),
                ('student_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_pref', to='project_allocation.student')),
            ],
        ),
        migrations.CreateModel(
            name='Peer_edges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(default='N', max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_peer', to='project_allocation.course')),
                ('peer_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_id_peer', to='project_allocation.student')),
                ('student_roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_peer', to='project_allocation.student')),
            ],
        ),
    ]
