# Generated by Django 3.2.8 on 2021-10-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0007_course_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
