# Generated by Django 3.2.8 on 2021-10-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0008_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'course_name')},
        ),
    ]
