# Generated by Django 3.2.8 on 2021-10-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0009_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
